# docker-compose.yml
  services:
    dashboard:
      image: biharibabu1/ecommerce-dashboard:1.0
      container_name: ecommerce-dashboard
      ports:
        - "80:80"
      environment:
        USER_HOST: 10.0.4.44
        PROFILE_HOST: 10.0.1.54 
        PRODUCT_HOST: 10.0.12.9
        CART_HOST: 10.0.1.27 
        ORDER_HOST: localhost
        PAYMENT_HOST: localhost
      restart: unless-stopped